name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: "Windows x64"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v3
        with:
          name: driver_ultraleap
          path: build/ultraleap
          if-no-files-found: error